[general]
YOUTUBE_SECRET = "AIzaSyAMmJwm780uNHbVS60CmwbO-SbpC8ZaT2sa"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1tMwMH_OgZcR9u3Hv-0DayOnb01aR5nxrFXbLiGgWdSw/edit?usp=sharing"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID or folder ID
type = "service_account"
project_id = "youtube-scrapping-441411"
private_key_id = "67e170be50efc1fb5b5fd1db187eb3784b8f1b80"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCqqh5IvAzfhHOy\n...<truncated>...\n-----END PRIVATE KEY-----\n"
client_email = "youtube-transcript@youtube-scrapping-441411.iam.gserviceaccount.com"
client_id = "114425788861446451124"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/youtube-transcript%40youtube-scrapping-441411.iam.gserviceaccount.com"
